name: Build and Run Docker Container

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build . -t my-app:latest

      - name: Run Docker container in the background
        run: docker run -d -p 8000:8000 my-app:latest

      - name: Tunnel with Serveo
        run: |
          nohup ssh -o StrictHostKeyChecking=no -R 80:localhost:8000 serveo.net &
      - name: Keep job running
        run: |
          while true; do
            sleep 60
          done
